@echo off
echo Clearing cache...
if exist .next rmdir /s /q .next

echo Releasing port 3000 if in use...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :3000 ^| findstr LISTENING 2^>nul') do (
    echo Killing process %%a occupying port 3000...
    taskkill /f /pid %%a >nul 2>&1
)

echo Installing dependencies...
npm install
echo Starting CodeTogether...
npm run dev
